Dont assume the request format is set. Some bots dont set it (e.g., socbot search@socbay.com), which results in a NoMethodError: undefined method `html?' for nil:NilClass